// Code generated by ent, DO NOT EDIT.

package provisioningstep

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gen0cide/laforge/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldLTE(FieldID, id))
}

// StepNumber applies equality check predicate on the "step_number" field. It's identical to StepNumberEQ.
func StepNumber(v int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldEQ(FieldStepNumber, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldNotIn(FieldType, vs...))
}

// StepNumberEQ applies the EQ predicate on the "step_number" field.
func StepNumberEQ(v int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldEQ(FieldStepNumber, v))
}

// StepNumberNEQ applies the NEQ predicate on the "step_number" field.
func StepNumberNEQ(v int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldNEQ(FieldStepNumber, v))
}

// StepNumberIn applies the In predicate on the "step_number" field.
func StepNumberIn(vs ...int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldIn(FieldStepNumber, vs...))
}

// StepNumberNotIn applies the NotIn predicate on the "step_number" field.
func StepNumberNotIn(vs ...int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldNotIn(FieldStepNumber, vs...))
}

// StepNumberGT applies the GT predicate on the "step_number" field.
func StepNumberGT(v int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldGT(FieldStepNumber, v))
}

// StepNumberGTE applies the GTE predicate on the "step_number" field.
func StepNumberGTE(v int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldGTE(FieldStepNumber, v))
}

// StepNumberLT applies the LT predicate on the "step_number" field.
func StepNumberLT(v int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldLT(FieldStepNumber, v))
}

// StepNumberLTE applies the LTE predicate on the "step_number" field.
func StepNumberLTE(v int) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.FieldLTE(FieldStepNumber, v))
}

// HasStatus applies the HasEdge predicate on the "Status" edge.
func HasStatus() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, StatusTable, StatusColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatusWith applies the HasEdge predicate on the "Status" edge with a given conditions (other predicates).
func HasStatusWith(preds ...predicate.Status) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newStatusStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProvisionedHost applies the HasEdge predicate on the "ProvisionedHost" edge.
func HasProvisionedHost() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProvisionedHostTable, ProvisionedHostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProvisionedHostWith applies the HasEdge predicate on the "ProvisionedHost" edge with a given conditions (other predicates).
func HasProvisionedHostWith(preds ...predicate.ProvisionedHost) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newProvisionedHostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasScript applies the HasEdge predicate on the "Script" edge.
func HasScript() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ScriptTable, ScriptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScriptWith applies the HasEdge predicate on the "Script" edge with a given conditions (other predicates).
func HasScriptWith(preds ...predicate.Script) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newScriptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommand applies the HasEdge predicate on the "Command" edge.
func HasCommand() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CommandTable, CommandColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommandWith applies the HasEdge predicate on the "Command" edge with a given conditions (other predicates).
func HasCommandWith(preds ...predicate.Command) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newCommandStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDNSRecord applies the HasEdge predicate on the "DNSRecord" edge.
func HasDNSRecord() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DNSRecordTable, DNSRecordColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDNSRecordWith applies the HasEdge predicate on the "DNSRecord" edge with a given conditions (other predicates).
func HasDNSRecordWith(preds ...predicate.DNSRecord) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newDNSRecordStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFileDelete applies the HasEdge predicate on the "FileDelete" edge.
func HasFileDelete() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, FileDeleteTable, FileDeleteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFileDeleteWith applies the HasEdge predicate on the "FileDelete" edge with a given conditions (other predicates).
func HasFileDeleteWith(preds ...predicate.FileDelete) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newFileDeleteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFileDownload applies the HasEdge predicate on the "FileDownload" edge.
func HasFileDownload() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, FileDownloadTable, FileDownloadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFileDownloadWith applies the HasEdge predicate on the "FileDownload" edge with a given conditions (other predicates).
func HasFileDownloadWith(preds ...predicate.FileDownload) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newFileDownloadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFileExtract applies the HasEdge predicate on the "FileExtract" edge.
func HasFileExtract() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, FileExtractTable, FileExtractColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFileExtractWith applies the HasEdge predicate on the "FileExtract" edge with a given conditions (other predicates).
func HasFileExtractWith(preds ...predicate.FileExtract) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newFileExtractStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnsible applies the HasEdge predicate on the "Ansible" edge.
func HasAnsible() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AnsibleTable, AnsibleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnsibleWith applies the HasEdge predicate on the "Ansible" edge with a given conditions (other predicates).
func HasAnsibleWith(preds ...predicate.Ansible) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newAnsibleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlan applies the HasEdge predicate on the "Plan" edge.
func HasPlan() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "Plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.Plan) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentTasks applies the HasEdge predicate on the "AgentTasks" edge.
func HasAgentTasks() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AgentTasksTable, AgentTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentTasksWith applies the HasEdge predicate on the "AgentTasks" edge with a given conditions (other predicates).
func HasAgentTasksWith(preds ...predicate.AgentTask) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newAgentTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGinFileMiddleware applies the HasEdge predicate on the "GinFileMiddleware" edge.
func HasGinFileMiddleware() predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, GinFileMiddlewareTable, GinFileMiddlewareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGinFileMiddlewareWith applies the HasEdge predicate on the "GinFileMiddleware" edge with a given conditions (other predicates).
func HasGinFileMiddlewareWith(preds ...predicate.GinFileMiddleware) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(func(s *sql.Selector) {
		step := newGinFileMiddlewareStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProvisioningStep) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProvisioningStep) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProvisioningStep) predicate.ProvisioningStep {
	return predicate.ProvisioningStep(sql.NotPredicates(p))
}
