// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gen0cide/laforge/ent/predicate"
	"github.com/gen0cide/laforge/ent/provisionedschedulestep"
)

// ProvisionedScheduleStepDelete is the builder for deleting a ProvisionedScheduleStep entity.
type ProvisionedScheduleStepDelete struct {
	config
	hooks    []Hook
	mutation *ProvisionedScheduleStepMutation
}

// Where appends a list predicates to the ProvisionedScheduleStepDelete builder.
func (pssd *ProvisionedScheduleStepDelete) Where(ps ...predicate.ProvisionedScheduleStep) *ProvisionedScheduleStepDelete {
	pssd.mutation.Where(ps...)
	return pssd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pssd *ProvisionedScheduleStepDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pssd.hooks) == 0 {
		affected, err = pssd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProvisionedScheduleStepMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pssd.mutation = mutation
			affected, err = pssd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pssd.hooks) - 1; i >= 0; i-- {
			if pssd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pssd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pssd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pssd *ProvisionedScheduleStepDelete) ExecX(ctx context.Context) int {
	n, err := pssd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pssd *ProvisionedScheduleStepDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: provisionedschedulestep.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: provisionedschedulestep.FieldID,
			},
		},
	}
	if ps := pssd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pssd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ProvisionedScheduleStepDeleteOne is the builder for deleting a single ProvisionedScheduleStep entity.
type ProvisionedScheduleStepDeleteOne struct {
	pssd *ProvisionedScheduleStepDelete
}

// Exec executes the deletion query.
func (pssdo *ProvisionedScheduleStepDeleteOne) Exec(ctx context.Context) error {
	n, err := pssdo.pssd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{provisionedschedulestep.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pssdo *ProvisionedScheduleStepDeleteOne) ExecX(ctx context.Context) {
	pssdo.pssd.ExecX(ctx)
}
