// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gen0cide/laforge/ent/repocommit"
	"github.com/gen0cide/laforge/ent/repository"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/google/uuid"
)

// RepoCommit is the model entity for the RepoCommit schema.
type RepoCommit struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int `json:"revision,omitempty"`
	// Hash holds the value of the "hash" field.
	Hash string `json:"hash,omitempty"`
	// Author holds the value of the "author" field.
	Author object.Signature `json:"author,omitempty"`
	// Committer holds the value of the "committer" field.
	Committer object.Signature `json:"committer,omitempty"`
	// PgpSignature holds the value of the "pgp_signature" field.
	PgpSignature string `json:"pgp_signature,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// TreeHash holds the value of the "tree_hash" field.
	TreeHash string `json:"tree_hash,omitempty"`
	// ParentHashes holds the value of the "parent_hashes" field.
	ParentHashes []string `json:"parent_hashes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RepoCommitQuery when eager-loading is set.
	Edges RepoCommitEdges `json:"edges"`

	// vvvvvvvvvvvv CUSTOM vvvvvvvvvvvv
	// Edges put into the main struct to be loaded via hcl
	// RepoCommitToRepository holds the value of the RepoCommitToRepository edge.
	HCLRepoCommitToRepository *Repository `json:"RepoCommitToRepository,omitempty"`
	// ^^^^^^^^^^^^ CUSTOM ^^^^^^^^^^^^^
	repository_repository_to_repo_commit *uuid.UUID
	selectValues                         sql.SelectValues
}

// RepoCommitEdges holds the relations/edges for other nodes in the graph.
type RepoCommitEdges struct {
	// RepoCommitToRepository holds the value of the RepoCommitToRepository edge.
	RepoCommitToRepository *Repository `json:"RepoCommitToRepository,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// RepoCommitToRepositoryOrErr returns the RepoCommitToRepository value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RepoCommitEdges) RepoCommitToRepositoryOrErr() (*Repository, error) {
	if e.loadedTypes[0] {
		if e.RepoCommitToRepository == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: repository.Label}
		}
		return e.RepoCommitToRepository, nil
	}
	return nil, &NotLoadedError{edge: "RepoCommitToRepository"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RepoCommit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case repocommit.FieldAuthor, repocommit.FieldCommitter, repocommit.FieldParentHashes:
			values[i] = new([]byte)
		case repocommit.FieldRevision:
			values[i] = new(sql.NullInt64)
		case repocommit.FieldHash, repocommit.FieldPgpSignature, repocommit.FieldMessage, repocommit.FieldTreeHash:
			values[i] = new(sql.NullString)
		case repocommit.FieldID:
			values[i] = new(uuid.UUID)
		case repocommit.ForeignKeys[0]: // repository_repository_to_repo_commit
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RepoCommit fields.
func (rc *RepoCommit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case repocommit.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				rc.ID = *value
			}
		case repocommit.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				rc.Revision = int(value.Int64)
			}
		case repocommit.FieldHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hash", values[i])
			} else if value.Valid {
				rc.Hash = value.String
			}
		case repocommit.FieldAuthor:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rc.Author); err != nil {
					return fmt.Errorf("unmarshal field author: %w", err)
				}
			}
		case repocommit.FieldCommitter:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field committer", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rc.Committer); err != nil {
					return fmt.Errorf("unmarshal field committer: %w", err)
				}
			}
		case repocommit.FieldPgpSignature:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pgp_signature", values[i])
			} else if value.Valid {
				rc.PgpSignature = value.String
			}
		case repocommit.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				rc.Message = value.String
			}
		case repocommit.FieldTreeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tree_hash", values[i])
			} else if value.Valid {
				rc.TreeHash = value.String
			}
		case repocommit.FieldParentHashes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parent_hashes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rc.ParentHashes); err != nil {
					return fmt.Errorf("unmarshal field parent_hashes: %w", err)
				}
			}
		case repocommit.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field repository_repository_to_repo_commit", values[i])
			} else if value.Valid {
				rc.repository_repository_to_repo_commit = new(uuid.UUID)
				*rc.repository_repository_to_repo_commit = *value.S.(*uuid.UUID)
			}
		default:
			rc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RepoCommit.
// This includes values selected through modifiers, order, etc.
func (rc *RepoCommit) Value(name string) (ent.Value, error) {
	return rc.selectValues.Get(name)
}

// QueryRepoCommitToRepository queries the "RepoCommitToRepository" edge of the RepoCommit entity.
func (rc *RepoCommit) QueryRepoCommitToRepository() *RepositoryQuery {
	return NewRepoCommitClient(rc.config).QueryRepoCommitToRepository(rc)
}

// Update returns a builder for updating this RepoCommit.
// Note that you need to call RepoCommit.Unwrap() before calling this method if this RepoCommit
// was returned from a transaction, and the transaction was committed or rolled back.
func (rc *RepoCommit) Update() *RepoCommitUpdateOne {
	return NewRepoCommitClient(rc.config).UpdateOne(rc)
}

// Unwrap unwraps the RepoCommit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rc *RepoCommit) Unwrap() *RepoCommit {
	_tx, ok := rc.config.driver.(*txDriver)
	if !ok {
		panic("ent: RepoCommit is not a transactional entity")
	}
	rc.config.driver = _tx.drv
	return rc
}

// String implements the fmt.Stringer.
func (rc *RepoCommit) String() string {
	var builder strings.Builder
	builder.WriteString("RepoCommit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rc.ID))
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", rc.Revision))
	builder.WriteString(", ")
	builder.WriteString("hash=")
	builder.WriteString(rc.Hash)
	builder.WriteString(", ")
	builder.WriteString("author=")
	builder.WriteString(fmt.Sprintf("%v", rc.Author))
	builder.WriteString(", ")
	builder.WriteString("committer=")
	builder.WriteString(fmt.Sprintf("%v", rc.Committer))
	builder.WriteString(", ")
	builder.WriteString("pgp_signature=")
	builder.WriteString(rc.PgpSignature)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(rc.Message)
	builder.WriteString(", ")
	builder.WriteString("tree_hash=")
	builder.WriteString(rc.TreeHash)
	builder.WriteString(", ")
	builder.WriteString("parent_hashes=")
	builder.WriteString(fmt.Sprintf("%v", rc.ParentHashes))
	builder.WriteByte(')')
	return builder.String()
}

// RepoCommits is a parsable slice of RepoCommit.
type RepoCommits []*RepoCommit
