// laforge-agent's build script: bakes a per-team "chaff" blob into the
// compiled binary so two teams' agent binaries differ structurally, not
// just in the per-host identity bytes internal/agentfactory.PatchBinary
// overwrites afterward. The exact gap this closes: "compile once per platform, reused across every
// team, with only a per-host identity patched in" left every team on the
// same team running byte-identical binaries outside the patched region --
// trivially diffable to find the identity blob's own offset. A patch
// alone can never fix this: PatchBinary only overwrites a fixed-size
// region in place, it cannot change function layout, section sizes, or
// symbol offsets, which is exactly what "structurally different" means.
// Closing this gap for real therefore needs a real per-team *compile*,
// not another patch -- this file, plus src/chaff.rs, is that compile step.
//
// cmd/laforge-agent-factory's `build --team <id>` flag is the real
// caller: it derives a salt via internal/agentfactory.TeamSalt(teamID)
// and sets LAFORGE_TEAM_SALT before invoking `cargo build`, so the
// "compile once per team per platform, then patch per host" shape
// this produces -- one real
// compile per team (this file), reused across every host in that team
// via the existing fast identity patch (internal/agentfactory.PatchBinary,
// unchanged).
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let salt = env::var("LAFORGE_TEAM_SALT").unwrap_or_else(|_| {
        // No team salt set: a plain `cargo build`/`cargo test`/`cargo
        // clippy`, or cmd/laforge-agent-factory's `build` run without
        // --team. Falls back to a fixed value so local iteration, CI,
        // and every existing test that builds the agent with a plain
        // `cargo build --release` (internal/agentfactory's and
        // internal/gateway's own real-binary tests) keep building
        // exactly the binary they always have -- this is purely
        // additive, never a required step.
        "dev-unset-team-salt".to_string()
    });

    // A simple, dependency-free (no extra crate just for a build script)
    // deterministic expansion of the salt string into a pseudo-random
    // byte/number stream -- xorshift64*, seeded from an FNV-1a hash of
    // the salt. Not cryptographic, and doesn't need to be: its only job
    // is to vary compiled bytes *and layout* per team, never to hide or
    // protect anything by itself (that's the identity blob's job, and
    // it's unrelated to this).
    let mut state: u64 = 0xcbf29ce484222325;
    for b in salt.as_bytes() {
        state ^= *b as u64;
        state = state.wrapping_mul(0x100000001b3);
    }
    let mut next = move || {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        state
    };

    // The chaff blob's LENGTH varies with the salt, not just its
    // contents -- a fixed-size array whose bytes merely differ would
    // still change .rodata's contents but leave every symbol laid out
    // after it at the same relative offset across every team's build.
    // Varying the length shifts everything laid out after it, which is
    // the concrete thing that defeats a naive "diff two teams' binaries
    // and see what's different" pass: the diff isn't a small, contiguous
    // region anymore.
    let len = 2048 + (next() % 4096) as usize;
    let mut bytes = Vec::with_capacity(len);
    for _ in 0..len {
        bytes.push((next() & 0xff) as u8);
    }

    // A handful of small "chaff" functions with salt-derived constants,
    // so the compiler can't fold them into one shared body or dead-code-
    // eliminate them independently -- their combined output is folded
    // into a real value (see src/chaff.rs's perturb(), used by main.rs
    // to jitter the reconnect backoff) so LTO can't discard any of them
    // as unused. Varying the *count* of functions (not just their
    // constants) is what adds real symbols/code, not just data.
    let n_fns = 3 + (next() % 5) as usize; // 3-7 functions
    let mut fn_src = String::new();
    let mut call_src = String::new();
    for i in 0..n_fns {
        let c1 = next();
        let c2 = next() | 1; // odd, so wrapping_mul stays a real bijection-ish mix
        let rot = (next() % 63 + 1) as u32;
        fn_src.push_str(&format!(
            "#[inline(never)]\npub fn chaff_{i}(x: u64) -> u64 {{ (x ^ {c1}u64).wrapping_mul({c2}u64).rotate_left({rot}) }}\n\n",
        ));
        call_src.push_str(&format!("    acc = acc.wrapping_add(chaff_{i}(acc));\n"));
    }

    let generated = format!(
        "// Generated by build.rs from LAFORGE_TEAM_SALT -- see that file's own doc\n\
         // comment. Not hand-written, not meant to be edited directly; a fresh\n\
         // build regenerates this from scratch every time.\n\
         pub static CHAFF_BLOB: [u8; {len}] = {bytes:?};\n\n\
         {fn_src}\
         /// perturb folds every chaff_N function's output into `seed` so none of\n\
         /// them can be optimized out as dead code, and returns a value derived\n\
         /// from both the blob and the functions. Called once at startup and\n\
         /// mixed into a value that's allowed to vary (see main.rs's reconnect\n\
         /// jitter) -- never anything that affects wire protocol behavior.\n\
         pub fn perturb(seed: u64) -> u64 {{\n\
         \u{20}\u{20}\u{20}\u{20}let mut acc = seed ^ CHAFF_BLOB[0] as u64 ^ ((CHAFF_BLOB[CHAFF_BLOB.len() - 1] as u64) << 8);\n\
         {call_src}\
         \u{20}\u{20}\u{20}\u{20}acc\n\
         }}\n",
    );

    let out_dir = env::var("OUT_DIR").expect("cargo always sets OUT_DIR for a build script");
    let dest = Path::new(&out_dir).join("chaff.rs");
    fs::write(&dest, generated).expect("writing generated chaff.rs");

    // Rebuild whenever the team salt actually changes -- without this,
    // cargo has no way to know a plain `cargo build --release` with a
    // new LAFORGE_TEAM_SALT needs to regenerate chaff.rs and relink, and
    // would happily serve a stale cached binary from the last salt.
    println!("cargo:rerun-if-env-changed=LAFORGE_TEAM_SALT");
}
